race condition with host keys

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -56,9 +56,12 @@ jobs:
 
           # prepare Traefik directory
           ssh -o StrictHostKeyChecking=no root@$NEW_SERVER_IPV4 "\
-            mkdir -p traefik/logs || true"
+            mkdir -p traefik/logs || true &&
+            cloud-init status --wait  > /dev/null 2>&1
+            [ $? -ne 0 ] && echo 'Cloud-init failed' && exit 1
+            echo 'Cloud-init succeeded at ' `date -R`  > /home/ubuntu/post-cloud-init.log"
 
-          scp scripts/dynamic_conf.yml root@$NEW_SERVER_IPV4:~/traefik/
+          scp -o StrictHostKeyChecking=no scripts/dynamic_conf.yml root@$NEW_SERVER_IPV4:~/traefik/
 
           # New server is up and running - prepare the old one for death
           # retrieve current deployment priv key
@@ -72,10 +75,6 @@ jobs:
 
           # deploy traefik to droplet - sleep here is to let cloudinit finish
           ssh root@$NEW_SERVER_IPV4 "\
-            # Block until cloud-init completes
-            cloud-init status --wait  > /dev/null 2>&1
-            [ $? -ne 0 ] && echo 'Cloud-init failed' && exit 1
-            echo 'Cloud-init succeeded at ' `date -R`  > /home/ubuntu/post-cloud-init.log
             docker rm -f traefik || true && \
             docker run -d --restart=always \
               -e DO_AUTH_TOKEN=${{ secrets.CTX_DIGITALOCEAN_DNS_TOKEN }} \
